### ISSUE TITLE
Examples to use pytapo

### ISSUE THREAD

**Issue by ShanmugaCA** [JurajNyiri/pytapo#21]
Hi @JurajNyiri!

Can you please add some examples to use the implementation ?

I could make the tapo.calibrateMotor() and unable to view the video stream in python,

best 
Shanmuga

**Comment by JurajNyiri** [comment]
Hello, this is a supporting library for https://github.com/JurajNyiri/HomeAssistant-Tapo-Control . You can check that code to see how its used. Unfortunately I do not have enough time to write examples in here right now. If anyone wants to do that PRs are welcomed.

**Comment by uberubert** [comment]
I was also looking for usage instructions but quickly got lost in a blind search. It's fine that you don't have time to make examples but atleast point people in a getting-started direction. Not trying to be critical, just trying to suggest that your documentation could make it easier for new people to get started. Your efforts would mean nothing to people who can't (or lack patience to) make use of your work.

For perspective: The current README.md is 30% installation instructions and 70% contribution instructions with credits and disclaimers. The emphasis seems to be on contribution rather than usage.

**Suggestions, based on how I eventually found my way to a starting point:**
- Addition to README.md: Info on the path and link to the __init__.py file containing the Tapo class. This class is sort of self-documenting in that it contains somewhat understandable function names. For a while I didn't even consider checking the class because the lack of instructions were demotivating. Then I had to go guess and search for where this class is located. Maybe I'm just lacking python competency..?
- Addition to README.md: Mention that this is a supporting library for the homeassistant tapo control repo. Perhaps include a sentence on the purpose of this repo and it's intended use-case(s). Perhaps also include some info on why someone would use this repo over the homeassistant repo, or vice versa.

I'm also wondering if tp-link themselves offer any kind of API-documentation. I seem incapable of finding official docs. Is this repo the result of reverse engineering?
